name: Capital Urbano
favicon: null
layout_spectrum: 0.3878345771227032
typography_spectrum: 0.92479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9b298'
    - '#bf2e1b'
    - '#ca5140'
    - '#e0968b'
  brandStrength: 0.8125
  lightness: 0.9375834532547742
  saturation: 0.625
  rhythmicContrast: 0.7244315557181835
purpose: []
